version: '3.9'
services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile.dev
    image: nextjs
    container_name: nextjs
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./nextjs:/app
      - nextjs_node_modules:/app/node_modules
    ports:
      - 3000:3000
      # コンテナ内部のdnsではバックエンド側のドメインを名前解決できないため
    dns:
      - 'localhost:127.0.0.1'
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile.dev
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-db-store:/var/lib/mysql

  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile.dev
    image: mail
    container_name: mail
    ports:
      - '8025:8025'
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
volumes:
  nextjs_node_modules:
  mysql-db-store:
  maildir: {}
